-- 方案 C S1：會員補 ERP 欄位（客戶資料）
ALTER TABLE members ADD COLUMN IF NOT EXISTS client_code TEXT;
ALTER TABLE members ADD COLUMN IF NOT EXISTS uniform_num TEXT;
ALTER TABLE members ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT '台幣';
ALTER TABLE members ADD COLUMN IF NOT EXISTS tax_type TEXT;
ALTER TABLE members ADD COLUMN IF NOT EXISTS taxrate NUMERIC DEFAULT 0.05;
ALTER TABLE members ADD COLUMN IF NOT EXISTS prepaid NUMERIC DEFAULT 0;
ALTER TABLE members ADD COLUMN IF NOT EXISTS client_cat TEXT;

CREATE INDEX IF NOT EXISTS idx_members_client_code ON members(client_code) WHERE client_code IS NOT NULL;
